postgres:
  build: docker-compose/postgres
  ports:
    - "5434:5432"
  environment:
    POSTGRES_PASSWORD: insecure
  
elasticsearch:
  build: docker-compose/elasticsearch
  command: elasticsearch -Des.node.name="Atlas"
  ports:
    - "9200:9200"
    - "9300:9300"
