postgres:
  build: docker-compose/postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: insecure
  
elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"