version: "3.0"
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: bag
    volumes:
      - ./backups:/tmp/backups
    extra_hosts:
      admin.datapunt.amsterdam.nl: 10.99.157.24

  elasticsearch:
    image: amsterdam/elasticsearch6
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/bag:${ENVIRONMENT}
    links:
      - database:database
      - elasticsearch:elasticsearch
    user: root
    environment:
      DATABASE_NAME: bag
      DATABASE_USER: bag
      DATABASE_PASSWORD: insecure
      METADATA_URL:
      BAG_OBJECTSTORE_PASSWORD:
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-import-db.sh"
