database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: atlas

elasticsearch:
  image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  volumes:
    - ./backups/elasticsearch:/tmp/backups
  user: root
  command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

tests:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
    BAG_OBJECTSTORE_PASSWORD:
    METADATA_URL: ""
    JWT_SHARED_SECRET_KEY: insecure
  command: bash -c "/app/docker-wait.sh && python manage.py test"
