database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: atlas

elasticsearch:
  image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  volumes:
    - ./backups/elasticsearch:/tmp/backups
  user: root
  command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

tests:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
    OS_PASSWORD_BAG: insecure
    METADATA_URL: ""
  command: bash -c "/app/docker-wait.sh && python manage.py test"

importer:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
    OS_PASSWORD_BAG: insecure
    METADATA_URL: "${METADATA_URL}"
  command: >
    bash -c "/app/docker-wait.sh \
            && python objectstore/objectstore.py \
            && python manage.py migrate \
            && python manage.py run_import --no-index \
            && python manage.py elastic_indices --delete"

importer_el1:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  volumes:
    - /mnt/data/diva_import:/app/diva
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices gebieden wkpb --build \
            && python manage.py elastic_indices bag brk --partial=1/3 --build"

importer_el2:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  volumes:
    - /mnt/data/diva_import:/app/diva
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices bag brk --partial=2/3 --build"

importer_el3:
  build: ..
  links:
    - database:database
    - elasticsearch:elasticsearch
  volumes:
    - /mnt/data/diva_import:/app/diva
  environment:
    DATABASE_NAME: atlas
    DATABASE_USER: atlas
    DATABASE_PASSWORD: insecure
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices bag brk --partial=3/3 --build"

db-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  volumes:
    - /mnt/dumps:/tmp/backups
  command: >
    bash -c "echo db:5432:atlas:atlas:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -t bag* \
                        -t brk* \
                        -t wkpb* \
                        -t geo*  \
                        -T django*  \
                        -T auth*  \
                        -T oauth2*  \
                        -U atlas \
                        -h db -p 5432 \
                        atlas > /tmp/backups/bag.dump"

el-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  links:
    - elasticsearch:el
  volumes:
    - ./backups/elasticsearch:/tmp/backups
  user: root
  command: >
    bash -c "curl -X PUT http://el:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
            && curl -X PUT http://el:9200/_snapshot/backup/atlas?wait_for_completion=true -d '{ \"indices\": \"bag,brk,nummeraanduiding\" }' \
            && chown -R 997:997 /tmp/backups"

web-static:
  build: ..
  user: root
  volumes:
    - /mnt/data/static/:/static/
  command: python manage.py collectstatic --noinput
